---
  # Task para a instalação do nginx e repositório

  - name: Configurar o repositório
    yum:
      name: epel-release
      state: present

  - name: Instalar o nginx
    yum:
      name: nginx
      state: present
      
  - name: Iniciar nginx
    service:
      name: nginx
      state: started    
