---
  # Task para a instalação do nginx e repositório
  - name: Configurar o repositório
    yum:
      name: epel-release
      state: present

  # Task para instalação do nginx
  - name: Instalar o nginx
    yum:
      name: nginx
      state: present

  # Task para iniciar o nginx
  - name: Iniciar nginx
    service:
      name: nginx
      state: started

  # Task para criar o arquivo php info para testes
  - name: Criando arquivo php info
    copy:
      dest: "/usr/share/nginx/html/info.php"
      content: <?php phpinfo() ?>

  # Task desabilitar SELinux
  - name: Desabilitar o SELinux
    selinux:
      state: disabled

  # Task para copiar o arquivo de configuração do nginx para o diretório
  - name: Copiar o arquivo de configuração do nginx para o diretório
    template: src=nginx.conf dest=/etc/nginx/

  # Task para reiniciar o serviço do nginx
  - name: Reiniciar o serviço do nginx
    service: name=nginx state=started enabled=true
