---
  # Task para instalação do PHP-FPM e suas dependências
  - name: Instalar php-fpm e suas dependências
    yum: name={{item}} state=present
    with_items:
      - php
      - php-fpm
      - php-mysql

 # Task iniciar o serviço do PHP-FPM
  - name: Iniciar o serviço do php-fpm
    service:
     name: php-fpm
     state: started

 # Task para copiar o arquivo de configuração do php-fpm para o diretório
  - name: Copiar o arquivo de configuração do www.conf
    template: src=www.conf dest=/etc/php-fpm.d/

 # Task para copiar o arquivo de configuração do php.ini para o diretório
  - name: Copiar o arquivo de configuração do php.ini
    template: src=php.ini dest=/etc

 # Task para reiniciar o serviço do php-fpm
  - name: Reiniciar o serviço php-fpm
    service: name=php-fpm state=started enabled=true
