- name: Rivendel Tecnologia Projeto Ansible + Vagrant Instalação mariadb, WordPress, Nginx e PHP-FPM Seguindo boas práticas.
  hosts: all
  user: vagrant
  become: yes

  roles:
    - php
    - nginx
    - mariadb
    - wordpress 
