---
  # Task para fazer o download do wordpress no diret贸rio tmp
  - name: Download do wordpress para o diret贸rio tmp
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/usr/share/nginx/html/wordpress.tar.gz


  - name: Descompactar o arquivo do wordpress
    unarchive:
      src: /home/marcos_fernando/lab/ansible-vagrant/projeto-ansible-vagrant/roles/wordpress/tasks/wordpress-4.9.7.tar.gz
      dest: /usr/share/nginx/html/
      remote_src: yes

  # Task para extrair o arquivo wordpress.tar.gz para o diret贸rio html
  #- name: Extrair o arquivo wordpress.tar.gz para o diret贸rio html
  #  unarchive:
  #    src: /usr/share/nginx/html/wordpress.tar.gz
  #    dest: /usr/share/nginx/html/
