---
  # Task para instalação do PHP-FPM e suas dependências

  - name: Instalar php-fpm e suas dependências
    yum: name={{item}} state=present
    with_items:
      - php
      - php-fpm
      - php-enchant
      - php-IDNA_Convert
      - php-mbstring
      - php-mysql
      - php-PHPMailer
      - php-process
      - php-simplepie
      - php-xml
